name: Build & Package Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      # Assuming you have tests directory
      run: |
        if [ -d "tests" ]; then pytest --maxfail=1 --disable-warnings -q; fi

    - name: Build Docker image
      run: |
        docker build -t quantumrequest-backend:latest .

    - name: Save Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: quantumrequest-backend-image
        path: |
          $(docker save quantumrequest-backend:latest -o image.tar)
          image.tar

    - name: Archive source code
      uses: actions/upload-artifact@v3
      with:
        name: source-code-archive
        path: |
          .
          !.git/**
          !.github/**
